// frontend/vue/src/LikeButton2.vue
<template>
	<button @click="handleLike">👍 讚 {{ likes }}</button>
</template>

<script setup>
import { ref, onBeforeMount } from "vue";
import api from "./api"; // 引入設定好的 axios 實例

const likes = ref(0); // 使用 ref 來創建響應式變數

onBeforeMount(async () => {
	try {
		const response = await api.get("/likes"); // 使用 axios 實例發起 GET 請求
		likes.value = response.data.likes;
	} catch (error) {
		console.error("Failed to fetch likes:", error);
	}
});

const handleLike = async () => {
	likes.value += 1; // 樂觀地更新 likes 值
	try {
		api.post("/likes"); // 使用 axios 實例發起 POST 請求
	} catch (error) {
		console.error("Failed to add like:", error);
	}

	const response = await api.get("/likes");
	if (response.data.likes !== likes.value) {
		likes.value = response.data.likes; // 更新 likes 變數
		return;
	}
};
</script>

// frontend/react/src/LikeButton2.tsx
import React from "react";
import useSWR, { mutate } from "swr";
import api from "./api"; // 引入你的 axios 實例

const fetcher = (url: string) => api.get(url).then((res) => res.data);

const LikeButton2: React.FC = () => {
	const { data } = useSWR("/likes", fetcher);

	// 處理點讚功能
	const handleLike = async () => {
		try {
			api.post("/likes"); // 假設後端在點讚後會自動更新數量
			mutate("/likes", { likes: data.likes + 1 }, true); // 臨時更新本地數據
		} catch (error) {
			console.error("Failed to add like:", error);
		}
	};

	return <button onClick={handleLike}>👍 讚 {data.likes}</button>;
};

export default LikeButton2;
